import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs';
import Navbar from "@/components/Navbar";
import { Roboto as RobotoFont } from 'next/font/google';

const roboto = RobotoFont({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-roboto',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className={roboto.variable}>
      <body
         className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <Navbar />
        {children}
        
      </body>
    </html>
    </ClerkProvider>
  );
}
